### ISSUE TITLE
Ability to choose other fonts

### ISSUE THREAD

**Issue by kpcenti** [ggtylerr/divolt-desktop#4]
Is it possible to implement the option to use other fonts other than the one listed?

**Comment by ggtylerr** [comment]
Like #3, this is also an upstream issue. But you can also use another workaround with CSS overrides.
1. Get the font you want to use
2. Make/get a CSS import rule (the quickest way to do this is to use a font from [Google Fonts](https://fonts.google.com), select a font, and on the sidebar, select "`@import`"
3. Go into Divolt, settings, appearance, advanced, custom CSS, and paste this:
```css
@import url('https://fonts.googleapis.com/css2?family=Nunito&display=swap');
* { --font: "Nunito" }
```
4. Replace the first line `@import url(blah blah blah)` with the import rule
5. Replace "Nunito" in the 2nd line with the font family name
